engines:
  coffeelint:
    enabled: true
  eslint:
    enabled: false
  csslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
    - "**.coffee"
    - "**.html"
    - "**.css"
exclude_paths:
  - "js/lib/**"
