engines:
  coffeelint:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
    - **.coffee
    - "**.html"
    - "**.css"
exclude_paths:
  - js/lib/**
